### ISSUE TITLE
some github notifications have incorrect links

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [rafaelmardojai/forge-sparks#23]
When clicking on a notification from github (for example, from a PR with `"reason": "review_requested"`). The link leads to `https://github.com/org/repo/pulls` instead of `https://github.com/org/repo/pull/123`. I think this used to work in the past.

From my testing, this only seems to affect private repos.

I can share raw API data for notifications in private if that would help.

**Comment by rafaelmardojai** [comment]
Yeah, it is documented in the Github access token setup dialog of the app, if you work with private repos you need to grant the full `repo` scope, otherwise the app doesn't have permission to get the pull request details (html url, status, etc). The current link is a fallback when the details request fails.

**Comment by SoMuchForSubtlety** [comment]
Thanks for the quick response  :)
